### ISSUE TITLE
Support catkin-tools

### ISSUE THREAD

**Issue by marcoesposito1988** [duckietown/hatchery#16]
First of all, thanks for the great plugin! It makes life much easier.

It would be great if it could support catkin-tools (catkin build) in alternative to plain catkin (catkin_make).

It should be possible to find the correct command by checking for the existance of the directory .catkin_tools inside the workspace root. 

I can start working on a pull request to implement this.

**Comment by breandan** [comment]
Hi Marco, thanks for your feedback! It would be great to have additional build support. We are currently working to integrate @paoloach's [ROS plugin](https://github.com/paoloach/ROS-JetBrains-Plugin) into Hatchery, which can be found in the [`paolo-integration` branch](https://github.com/duckietown/hatchery/tree/paolo-integration). It has some [limited support for catkin](https://github.com/duckietown/hatchery/blob/paolo-integration/src/main/kotlin/it/achdjian/plugin/ros/utils/Catkin.kt), but does not support catkin-tools directly. Contributions, of course, are highly welcome! If you are interested, please don't hesitate to look around and let me know if you have any questions.
