### ISSUE TITLE
Path separator is incorrect

### ISSUE THREAD

**Issue by airfield20** [duckietown/hatchery#18]
Path separator is in this file [RosPathTools.kt](https://github.com/duckietown/hatchery/blob/e31757cd098b1c4a9bf5a58f9164cf1a55dbea16/src/main/kotlin/edu/umontreal/hatchery/ros/RosPathTools.kt) defined on line 51 and used on line 201 is incorrect for clion 2019.1

This is the output when I click run launch file: 
```
sh -c "echo 'ROS workspace directory: /home/aaron/Humanoid/humanoid_ws' &&
      cd /home/aaron/Humanoid/humanoid_ws &&
      catkin_make &&
      echo 'Sourcing /home/aaron/Humanoid/humanoid_ws:devel:setup.sh' &&
      . /home/aaron/Humanoid/humanoid_ws:devel:setup.sh &&
      echo 'Available nodes:' &&
      rosnode list &&
      echo 'Available topics:' && ...
```

which eventually leads to this error:

```
Base path: /home/aaron/Humanoid/humanoid_ws
Source space: /home/aaron/Humanoid/humanoid_ws/src
Build space: /home/aaron/Humanoid/humanoid_ws/build
Devel space: /home/aaron/Humanoid/humanoid_ws/devel
Install space: /home/aaron/Humanoid/humanoid_ws/install
####
#### Running command: "make cmake_check_build_system" in "/home/aaron/Humanoid/humanoid_ws/build"
####
####
#### Running command: "make -j12 -l12" in "/home/aaron/Humanoid/humanoid_ws/build"
####
Sourcing /home/aaron/Humanoid/humanoid_ws:devel:setup.sh
sh: 5: .: Can't open /home/aaron/Humanoid/humanoid_ws:devel:setup.sh

Process finished with exit code 2
```
For some reason, it wants to use `:` to separate file paths...
Is this an easy fix?

**Comment by marcoesposito1988** [comment]
This should be the same as #13, and it should be solved already.

Are you using an old version of Hatchery?

**Comment by airfield20** [comment]
I just installed the plug-in directly from clion marketplace. Is that the most up to date version?

**Comment by breandan** [comment]
No, but you can download our [canary build](https://teamcity.jetbrains.com/repository/download/hatchery_buildplugin/.lastSuccessful/hatchery.zip?guest=1) and [install it from disk](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk). Hoping to release a new version to the plugin marketplace shortly. Thanks!

**Comment by airfield20** [comment]
Alright thanks, that fixed the issue.

**Comment by wandgibaut** [comment]
I have the same problem with Pycharm, even with the latest version (0.32) and installing from disk. Do you have another solution suggestion?
