### ISSUE TITLE
not found in root project `hatchery`

### ISSUE THREAD

**Issue by liampaull** [duckietown/hatchery#20]
What are the requirements about the location of the project on the file system with respect to the hatchery source code? The documentation that I have says I can specify an absolute path to my ROS package but this caused an error. 

Here's the output I received:
```
liam@couguar:~/hatchery$ ./gradlew runIde ~/dt-env-developer/src/Software/

FAILURE: Build failed with an exception.

* What went wrong:
Task '/home/liam/dt-env-developer/src/Software/' not found in root project 'hatchery'.
```

**Comment by breandan** [comment]
I think you are missing the `-Project` flag. Can you try this command from inside the `/home/liam/hatchery` directory and see what happens: `./gradlew runIde -Project=/home/liam/dt-env-developer/src/Software/`? (It might take a while the first time.)

**Comment by liampaull** [comment]
yes you are correct.
