### ISSUE TITLE
Not supported anymore in CLIOn 2023.02

### ISSUE THREAD

**Issue by nubertj** [duckietown/hatchery#34]
Hi all,
thanks a lot for this amazing plugin. It really made working with ROS launchfiles etc. much much easier for me over the past few years.
Unfortunately, it seems that it is not supported anymore in the latest CLION 2023.02... :/

Do you by any chance have any plans providing support for it?
Thanks a lot for this great service to the community!
![hatchery](https://github.com/duckietown/hatchery/assets/22931770/da3c5d94-8cf9-4b54-b22e-8752003b5c23)

**Comment by breandan** [comment]
Hi @nubertj, thanks for using Hatchery and your feedback! The good news is that @siilats submitted [a PR](https://github.com/duckietown/hatchery/pull/33) last year that I missed until now. I have updated it with minor changes and republished [the plugin](https://plugins.jetbrains.com/plugin/10290-hatchery/versions/stable/373754) to the JetBrains Plugin repository. This should nominally work with CLion `2023.2`, but may not support all of the original features.

Hatchery is mostly in maintenance mode at this time. I am no longer using ROS on a regular basis, and do not plan to add many new features in the near future. In case you may know someone who would be willing to support it going forward, please contact one of the Duckietown admins and I will be happy to assist however I can.

**Comment by nubertj** [comment]
Dear @breandan,
Thanks a lot for your fast action!
I just installed it and it all seems to work the same way it did before :)
Best,
Julian
