### ISSUE TITLE
Allow jumping to arbitrary file types

### ISSUE THREAD

**Issue by danmou** [duckietown/hatchery#4]
Currently, if you reference a .yaml file in a launch file, e.g. as below,
`<arg name="foo"  value="$(find some_package)/some/file.yaml"/>`
hatchery will allow you to jump to that file.
However, for some other extensions, for example `.info`, hatchery will mark the reference with red and say "unknown resource".

I would expect file referencing to work for any extension, as long as the file exists.

**Comment by breandan** [comment]
This should be fixed in the latest release, thank you for reporting.. Please open a new issue if you encounter a valid reference which is marked by Hatchery as unknown.
